Add page header and Metric components
earth-genome/foodtwin-global-app pull request #36
Opened 2024-08-30 03:31 UTC by oliverroick

Adding component we can use on item pages: The page header and the metrics. 

For review:

-  The rendered components are in http://localhost:3000/sandbox/components
- Usage examples are in `/src/app/sandbox/components/page.tsx` 

## Page header

<img width="496" alt="Screenshot 2024-08-30 at 13 04 59" src="https://github.com/user-attachments/assets/d676ce5b-e742-4853-9049-ed6305909534">

- Adds `PageHeader` component that takes title and type components and renders accordingly.
- The X button is currently a link to the globe view, but we can change that later to a button with custom onClick behaviour if needed. 

@faustoperez I added some longer names for the page titles. For example, Baden-Württemberg is a state in Germany and also a producing area. The name needs three lines if the country is included. I think, it still works well, but you might have a different opinion ;)

## Metrics

<img width="506" alt="Screenshot 2024-08-30 at 13 07 32" src="https://github.com/user-attachments/assets/d9be89e9-4318-43f2-850e-0fb62d985120">

(The top and bottom borders are only present in the sandbox to better visualise the spacing, in relation to the box edge. 

- Adds `PageSection`, which is a wrapper for a section of metrics and graphs.
- Adds `SectionHeader`, which renders the title of the section alongside an optional tooltip
- Adds `MetricRow`, which is a simple flex box wrapper for `Metric`
- Adds `Metric`, which renders a metric with label, value and unit. The value is formatted according to US locales. (@vgeorge  in the design there are what looks like estimated values (for example, `~123,220` ). Is there a reliable way to tell from the data, which values are estimated?)

2024-09-02 14:04 UTC, vgeorge requested changes
@oliverroick This looks nice! I added a few small comments. I like the convention of using `E...` and `I...` for enums and interfaces. Regarding the flow number, I'm currently working on the flow data ingestion, but I don't have an estimate right now. I expect to have this soon, and then we can work on improving the format separately.

@faustoperez Regarding the country codes, I'm leaning more towards 2-letter ISO codes, as they are more compact and recognizable than the 3-letter codes.

2024-09-03 06:35 UTC, oliverroick commented on src/app/components/PageHeader.tsx
> +function PageHeader({ title, type }: IPageHeader) {
:+1: I renamed this to `itemType`, since the item we're showing on the page dictates what we're showing on the page

2024-09-03 06:40 UTC, oliverroick commented
@faustoperez 

> That is great @oliverroick. Reviewing the designs with @wrynearson we thought about shortening the Admin 1 names and using the 3 digit code. For admin 0 names, they'll default to the full name. Is that feasible?

I have to defer to @vgeorge. It depends, which way the nodes are labelled in the database. If we have the country codes or if we're able to infer them from the labels in the data then it's no problem

2024-09-05 07:34 UTC, vgeorge approved these changes

2024-09-05 07:42 UTC, merged

2024-09-05 13:09 UTC, faustoperez commented
> @faustoperez Regarding the country codes, I'm leaning more towards 2-letter ISO codes, as they are more compact and recognizable than the 3-letter codes.

That is fine with me @vgeorge 👍